public enum SkillType : byte
{
    Unknown,
    HP,
    Knifesmanship,
    Swordsmanship,
    Axemanship,
    Hammermanship,
    Deftness,
    Strength,
    Archery,
    Mining,
    Smithing,
    Alchemy,
    Fishing,
    Woodcutting,
    Woodworking,
    Hunting,
    Culinary_Arts,
    Leatherworking,
    Construction
}